#!/bin/sh
#set -x
echo "❗❕ pre-push"

BRANCH_NAME=$(git branch --show-current)
if [ $BRANCH_NAME ]; then
    #-------------------------------------------------------------------------------------
    if [[ $BRANCH_NAME != @(dev|DEV|Dev|master|Master|qa|QA|Qa) ]]; then
        array=(${BRANCH_NAME//_/ })
        res=$(git ls-remote --exit-code --heads origin $BRANCH_NAME)
        if [[ $res ]]; then
            echo "Branch exists ✔";
        else
            if (( ${#array[@]} == 1 ))
            then
                echo "🚫 Please commit some changes and then push.";
                exit 1
            fi
        fi
    fi
    #-------------------------------------------------------------------------------------
    cd api
    echo "Restoring... ⏳";
    dotnet restore /clp:ErrorsOnly
    rc=$?
    if [[ $rc != 0 ]] ; then
        echo -e "🚫 Failed to restore the project, please fix this and push again. ❌"
        exit $rc
    fi
    echo "Restored successfully ✔"
    echo "Building... ⏳";
    dotnet build --no-restore -v q /clp:ErrorsOnly
    rc=$?
    if [[ $rc != 0 ]] ; then
        echo -e "🚫 Failed to build the project, please fix this and push again. ❌"
        exit $rc
    fi
    echo "Build Successfully ✔"
    cd ..
    #-------------------------------------------------------------------------------------
fi